### ISSUE TITLE
Relative paths no longer working

### ISSUE THREAD

**Issue by spfuller** [ChristianKohler/PathIntellisense#196]
My paths are no longer relative to my current folder since either the 2.6.1 or 2.7.0 update.

I used to be able to do `'./'` and the suggestion would be from my current folder. However it now always suggests from the workspace root folder. All of my settings are default.

**Comment by ChristianKohler** [comment]
Thank you @spfuller 

What is your OS? How does your extension config look like?

**Comment by AliaksanauRaman** [comment]
Same from my side.

I'm working in my angular project. I didn't add any specific configurations. I have only the ones which were there by default after executing `ng new my-app`.

**Comment by spfuller** [comment]
I’m using windows and the configuration is the defaults for PathIntellisense.

________________________________

**Comment by AliaksanauRaman** [comment]
The funny thing is that I've tried almost all of the 2.x.x versions and non of them worked.
Only 1.4.2 (the latest version before the major change) works fine for me.

@spfuller you can also try to use this one for now.

**Comment by ChristianKohler** [comment]
Thank you for the feedback.

I just tried to reproduce it. In this case i get the current folder and not the root:

https://user-images.githubusercontent.com/4374178/151701066-b0833023-f085-4150-9e33-340521d9f403.mov


In this case, it gives you the root folder instead of the current folder. Right?

Could you provide a small example with which I can reproduce it?

**Comment by AliaksanauRaman** [comment]
<img width="1439" alt="Screenshot 2022-01-30 at 14 18 09" src="https://user-images.githubusercontent.com/62064550/151701397-e5db0def-00e4-4a9f-853e-8d80278be3ce.png">
<img width="1438" alt="Screenshot 2022-01-30 at 14 18 30" src="https://user-images.githubusercontent.com/62064550/151701401-ad0103a4-5b76-4000-90ff-636f3e184fa9.png">

The first screenshot is taken with the extension of version 1.4.2 (everything works as expected).
The second one is taken with the extension of version 2.7.0 (the root folder of the workspace is shown).

**Comment by ChristianKohler** [comment]
Ok. I found the issue.

## Analysis

By default, PathIntellisense reads the baseUrl in the tsconfig.

For example, if the tsconfig looks like this:

```javascript
 {
 	"baseUrl": "src",
 }
 ```

"src" would we used as a key to `${workspace}/src`

 ```javascript
 {
 	import {} from 'src/mymodule';
 }
 ```

With Angular, the baseUrl is set to:

```javascript
 {
 	"baseUrl": "./",
 }
 ```

which means that the "key" is `./` which would then be resolved to `${workspace}/./`

The root of the problem is my over simplified solution to how I resolve the baseurl. I only add the baseurl to the mapping list like this:

```javascript
 {
 	key: "src",
        value: "${workspaceRoot}/src"
 }
 ```

Now when you type `"src/"`, the mapping resolved to `"${workspaceRoot}/src"` showing you all the children of src.

That approach works with all baseUrls, except `./` (afaik).

## Short term solution

Just disable the baseUrl support.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/4374178/151709593-68a3d229-b888-4a9f-95c2-4ea838708ba8.png">



## Long term solution

Not sure yet. I'd either have to rewrite the baseUrl logic to deal with `./` or just ignore it. Not sure.

Thank you all for you inputs. Hope disabling the baseUrl support work for you for now.

**Comment by spfuller** [comment]
Thanks, that short term solution works for me

**Comment by spfuller** [comment]
Thanks so much for this release. I can confirm that the issue is fixed with this new version.
