### ISSUE TITLE
Append / when path is a folder

### ISSUE THREAD

**Issue by moander** [ChristianKohler/PathIntellisense#23]
When
```html
<link rel="import" href="../bower_co<TAB>">
```

It should
```html
<link rel="import" href="../bower_components/">
```

Instead of
```html
<link rel="import" href="../bower_components">
```

Thanks for a great extension! :)

**Comment by edvinv** [comment]
+1
Also after folder selection you should open popup with subfolder/subfiles.

**Comment by ChristianKohler** [comment]
@moander: I added a / after a folder in previous versions but removed it. The reason was that it is more convenient to type another / instead of pressing ctrl+space again. See: https://github.com/ChristianKohler/PathIntellisense/issues/8 
@edvinv: VS Code doesn't allow it at the moment to trigger another code completion action after a selection.

**Comment by roblourens** [comment]
@ChristianKohler Is there a vscode bug to enable triggering code completion after selecting an item?

**Comment by ChristianKohler** [comment]
@roblourens Not that I know of
